<?php
 include(__DIR__ . DIRECTORY_SEPARATOR . 'en-base.php');
/**
    * PHP Array for English words
    */
array_push($badwords,
	'＆',
	'🖕',
	'グロ',
	'アナル',
	'スポット',
	'アスホール',
	'アナリングス',
	'カーマスートラ',
	'バック・スタイル',
	'グループ・セックス',
	'ล้างตู้เย็น',
	'หญิงชาติชั่ว',
	'1',
	'10',
	'13点',
	'2',
	'2g1c',
	'3p',
	'5',
	'a',
	'à',
	'aan',
	'aand',
	'aandu',
	'aardappels',
	'걸레같은년',    	// A bitch that is a rag
	'abortion',
	'aborto',
	'abortus', 		// Abortion
	'abrutie', 	// Idiot (feminine)
	'abruti', 	// Idiot (masculine)
	'achter',
	'achterlijk', 	// Retarded
	'acrotomophilia',
	'action',
	'afberen',
	'affanculo',
	'afgieteng',
	'aflebberen',
	'afrossen',
	'afrukken',
	'aftrekken',
	'afwerkplaats',
	'afzeiken',
	'afzuigen',
	'alabama',
	'alaskan',
	'albert',
	'alfred',
	'allupato',
	'allupato',
	'amador',
	'amcığa',
	'amcığı',
	'amcığın',
	'amcık',
	'amcıklar',
	'amcıklara',
	'amcıklarda',
	'amcıklardan',
	'amcıkları',
	'amcıkların',
	'amcıkta',
	'amcıktan',
	'amı',
	'amlar',
	'ämmää',         // hag, bitch; sg. partitive
	'ämmään',        // hag, bitch; sg. illative
	'ämmä',	// hag, bitch; sg. nominative
	'ämmällä',       // hag, bitch; sg. adessive
	'ämmälle',       // hag, bitch; sg. allative
	'ämmältä',       // hag, bitch; sg. ablative
	'ämmän',         // hag, bitch; sg. genitive
	'ämmässä',       // hag, bitch; sg. inessive
	'ämmästä',       // hag, bitch; sg. elative
	'ämmät',         // hag, bitch; pl. nominative
	'ämmiä',         // hag, bitch; pl. partitive
	'ämmien',        // hag, bitch; pl. genitive
	'ämmiin',        // hag, bitch; pl. illative
	'ämmillä',       // hag, bitch; pl. adessive
	'ämmille',       // hag, bitch; pl. allative
	'ämmiltä',       // hag, bitch; pl. ablative
	'ämmissä',       // hag, bitch; pl. inessive
	'ämmistä',       // hag, bitch; pl. elative
	'ammucchiata',
	'ammucchiata',
	'amor',
	'anal',
	'anale',
	'anale',
	'analplug',
	'analritter',
	'analsex',
	'and',
	'anderhalve',
	'anilingus',
	'쌍넘',     	// An insult (for men)
	'시팔놈',     	// An insult (for men)
	'쌍년',     	// An insult (for women)
	'시팔년',     	// An insult (for women)
	'니미랄',    	// An insulting word
	'anita',
	'anus',
	'ânus',
	'꼡성감대',     	// Any body part that reacts to sexual stimuli
	'äpärä',
	'apeshit',
	'aranha',
	'ariano',
	'arrapato',
	'arrapato',
	'arrusa',
	'arrusa',
	'arruso',
	'arruso',
	'arsch',
	'arschficker',
	'arschfotze',
	'arschgeige',
	'arschgesicht',
	'arschlecker',
	'arschloch',
	'arse',
	'arsehole',
	'arsle',
	'asbak',
	'asno',
	'aso',
	'ass',
	'assado',
	'assassin',
	'assatanato',
	'assatanato',
	'asshole',
	'assmunch',
	'åt',
	'aulaad',
	'aulad',
	'auto',
	'autoerotic',
	'baal',
	'babeland',
	'baby',
	'bæsj',
	'bagascia',
	'bagascia',
	'bagassa',
	'bagassa',
	'bagger',
	'bagging',
	'bagnarsi',
	'bagnarsi',
	'baise',	// Fuck
	'baisé',	// Fucked
	'baiser',
	'baiser',	// To fuck
	'bait',
	'balalao',
	'balatkar',
	'balcone',
	'baldracca',
	'baldracca',
	'balen',
	'balfasz',
	'balfaszok',
	'balfaszokat',
	'balfaszt',
	'ball',
	'balle',
	'balle',
	'ballen',
	'balls',
	'bander',
	'bang',
	'bangbros',
	'bareback',
	'barely',
	'barenaked',
	'barmok',
	'barmokat',
	'barmot',
	'barom',
	'bastard',
	'씹새끼',     	// Bastard
	'bastardo',
	'bastinado',
	'baszik',
	'batard',	// Bastard
	'batter',
	'battere',
	'battere',
	'battona',
	'battona',
	'bazmeg',
	'bbw',
	'bdsm',
	'beaner',
	'beaners',
	'beastiality',
	'beaver',
	'bedonderen',
	'befborstelg',
	'beffen',
	'bekken',
	'belazeren',
	'belino',
	'belino',
	'besodemieterd',
	'besodemieteren',
	'bestiality',
	'beti',
	'beurt',
	'bewb',
	'bhadva',
	'bhadve',
	'bhagat',
	'bhandve',
	'bhootni',
	'bhosad',
	'bhosada',
	'bhosadi',
	'bicha',
	'big',
	'biga',
	'biga',
	'bigornette',
	'bimbo',
	'bimbos',
	'birci',
	'bircide',
	'birciden',
	'birciler',
	'bircilerde',
	'bircilerden',
	'bircilere',
	'bircileri',
	'bircilerin',
	'bircinin',
	'birciye',
	'birciyi',
	'birdlock',
	'biscate',
	'bissexual',
	'bitch',
	'bitches',
	'bite',
	'bite',		// Dick
	'bitte',
	'black',
	'めくら',     	// Blind person, illiterate person
	'bloblos',
	'blonde',
	'bloody',
	'bloodyhell',
	'blow',
	'blowjob',
	'blue',
	'blumpkin',
	'boba',
	'bocchinara',
	'bocchinara',
	'bocchinaro',
	'bocchino',
	'bocchino',
	'boceta',
	'boemelen',
	'boerelul',
	'boerenpummelg',
	'bofilo',
	'bofilo',
	'boiata',
	'boiata',
	'bok',
	'bokkelul',
	'Bollera',
	'bollera',	// Lesbian
	'bollocks',
	'bolognese',
	'bondage',
	'boner',
	'bonze',
	'boob',
	'boobe',
	'boobies',
	'boobs',
	'booty',
	'bordel',
	'bordello',
	'bordello',
	'borracha',
	'bosneger', 	// Forest nigger
	'bosser',
	'bøsserøv',
	'bosta',
	'botergeil',
	'bougnoul',	// Sandnigger
	'bourré',
	'bourrée',
	'brackmard',
	'branlage',
	'branler',
	'branlette',
	'branleur',
	'branleur',	// Wanker
	'branleuse',
	'bratze',
	'braulio',
	'breasts',
	'brinca',
	'brinca',
	'broekhoesten',
	'brouter',
	'brown',
	'brugpieperg',
	'brunette',
	'bruning',
	'にんぴにん',  	// Brute
	'brutta',
	'bucaiolo',
	'bucaiolo',
	'budiùlo',
	'budiùlo',
	'buena',
	'buffelen',
	'bugger',
	'bugren',
	'bugri',
	'bugru',
	'buiten',
	'bukkake',
	'buksza',
	'bukszák',
	'bukszákat',
	'bukszát',
	'bulldyke',
	'bulle',
	'bullet',
	'bullshit',
	'bumbum',
	'bums',
	'bumsen',
	'bung',
	'bunghole',
	'buona',
	'buona donna',
	'búr',
	'ぶらく',		// Buraku
	'burdel',
	'burdelmama',
	'burne',	// Testicle
	'búrok',
	'burro',
	'busone',
	'busone',
	'busty',
	'butt',
	'buttcheeks',
	'butthole',
	'buttons',
	'buzna',
	'bychara',
	'byk',
	'bylsiä',
	'cabrao',
	'Cabron',
	'Cabrón',
	'cabrona',	// Dickhead (feminine)
	'cabronazo',	// Bastard
	'cabron',	// Dickhead
	'cabrón',	// Dickhead
	'caca',
	'Caca',
	'cacca',
	'cacca',
	'caccati',
	'caccati in mano e prenditi a schiaffi',
	'cacete',
	'caciocappella',
	'caciocappella',
	'cadavere',
	'cadavere',
	'cagar',
	'cagare',
	'cagare',
	'cagata',
	'cagata',
	'cagna',
	'cagna',
	'cailler',
	'call',
	'camel',
	'camgirl',
	'camisinha',
	'cammello',
	'cammello',
	'camslut',
	'camwhore',
	'cantante',
	'cappella',
	'cappella',
	'capulla',	// Asshole (feminine)
	'capullo',	// Asshole
	'caralho',
	'carciofo',
	'carciofo',
	'개지랄',     	// Careless dog (insult)
	'carità',
	'carità',
	'carl',
	'carpet',
	'carpetmuncher',
	'casci',
	'casci',
	'cawk',
	'cazzata',
	'cazzata',
	'cazzi',
	'cazzimma',
	'cazzimma',
	'cazzo',
	'cazzo',
	'cerveja',
	'chaatu',
	'chakke',
	'chatte',
	'chcanky',
	'checca',
	'checca',
	'cheque',
	'chernozhopyi',
	'chest',
	'chiappa',
	'chiappa',
	'chiasse',
	'chiavare',
	'chiavare',
	'chiavata',
	'chiavata',
	'chichi',	// Pussy
	'chick',
	'chier',
	'chier',	// To shit
	'chinaal',
	'しなじん',    	// Chinese person (offensive)
	'chink',
	'ちゃんころ',    // Chink
	'chinki',
	'chiottes',
	'choad',
	'chocho',	// Pussy
	'chochota',
	'chocolate',
	'chod',
	'chodu',
	'chooche',
	'choochi',
	'choos',
	'choot',
	'chootia',
	'chootiya',
	'chuche',
	'chuchi',
	'chudai',
	'chudan',
	'chuj',
	'chuja',
	'chujnia',
	'Chupada',
	'Chupapollas',
	'chupar',
	'Chupetón',
	'chusu',
	'chut',
	'chutad',
	'chutadd',
	'chutan',
	'chute',
	'chutia',
	'chutiya',
	'ĉiesulino',
	'ĉiesulo',
	'çingene',
	'Çingenede',
	'Çingeneden',
	'Çingeneler',
	'Çingenelerde',
	'Çingenelerden',
	'Çingenelere',
	'Çingeneleri',
	'Çingenelerin',
	'Çingenenin',
	'Çingeneye',
	'Çingeneyi',
	'ciospo',
	'ciospo',
	'ciota',
	'cipa',
	'circlejerk',
	'ciucciami',
	'ciucciami il cazzo',
	'clamps',
	'cleaver',
	'cleveland',
	'clit',
	'clito',
	'clitoris',
	'클리토리스',    	// Clitoris
	'clover',
	'club',
	'clusterfuck',
	'cocaína',
	'cock',
	'cocks',
	'cocksucker',
	'cocu',		// Cuckold
	'coglione',
	'coglione',
	'coglioni',
	'coglioni',
	'cojones',	// Testicles (slang)
	'cojon',	// Testicle (slang)
	'cojón',	// Testicle (slang)
	'colhoes',
	'come',
	'comepollas',	// Cocksucker
	'comer',
	'con',
	'cona',
	'concha',
	'Concha',
	'condom',
	'콘돔',     	// Condom
	'con',		// Idiot
	'connard',
	'connard',	// Idiot
	'connasse',
	'connasse',	// Stupid and annoying girl
	'conne',
	'conne',	// Idiot (feminine)
	'Coño',
	'cono',		// Cunt
	'coño',		// Cunt
	'consolo',
	'ひにん',     	// Contraception / Non-human (insult to Burakumin)
	'coon',
	'coons',
	'cooter',
	'Coprofagía',
	'coprolagnia',
	'coprophilia',
	'core',
	'cornhole',
	'corno',
	'cornuto',
	'cornuto',
	'couille',	// Ball (testicle)
	'couilles',
	'couillonne',	// Stupid (feminine)
	'couillon',	// Stupid (masculine)
	'cowgirl',
	'cozza',
	'cozza',
	'cramouille',
	'crap',
	'미친놈',    	// Crazy bastard
	'미친년',    	// Crazy bitch
	'creampie',
	'cresson',
	'crevard',	// Backstabber or Hobo, depending on the context
	'かたわ',     	// Cripple
	'csöcs',
	'csöcsök',
	'csöcsöket',
	'csöcsöt',
	'cu',
	'cul',
	'cul',		// Ass
	'culattina',
	'culattina',
	'culattone',
	'culattone',
	'culo',
	'culo',
	'Culo',
	'culo',		// Ass
	'cum',
	'čumět',
	'cumming',
	'cumshot',
	'cunnilingus',
	'cunt',
	'cup',
	'čurák',
	'cyc',
	'da',
	'damm',
	'dammit',
	'damn',
	'dar',
	'darkie',
	'da\'s',
	'date',
	'daterape',
	'de',
	'つんぼ',     	// Deaf person
	'debiel', 		// Moron, mentally retarded
	'debil',
	'déconne',
	'déconner',
	'deep',
	'deepthroat',
	'delg',
	'dendrophilia',
	'depp',
	'dhakkan',
	'di',
	'dick',
	'ちんぽ',     	// Dick
	'ちんちん',     	// Dick
	'dickhead',
	'しね',     	// Die
	'dig',
	'dildo',
	'di merda',
	'dingleberries',
	'dingleberry',
	'dio bestia',
	'dio cane',
	'diofek',
	'diofeka',
	'dio porco',
	'dirty',
	'discofitta',
	'ditalino',
	'ditalino',
	'diver',
	'dmuchać',
	'do',
	'dödel',
	'dog',
	'doggie',
	'doggiestyle',
	'doggy',
	'doggystyle',
	'いぬごろし',   	// Dog killer
	'dolboy\'eb',
	'dolcett',
	'dombo',
	'domination',
	'dominatrix',
	'dommes',
	'dong',
	'donkey',
	'donna',
	'donut',
	'double',
	'douche',
	'dp',
	'dra',
	'draaikontg',
	'drague',
	'dream',
	'dreck',
	'drecksau',
	'driehoog',
	'dritt',
	'drittsekk',
	'Drogas',
	'drolg',
	'drooggeiler',
	'droogkloot',
	'dršťka',
	'dry',
	'držka',
	'du',
	'due',
	'dum',
	'dummbatz',
	'dummkopf',
	'dupa',
	'dupek',
	'duperele',
	'duro',
	'duro',
	'dust',
	'dvda',
	'dyke',
	'dziwka',
	'e',
	'eat',
	'ebalnik',
	'ebalo',
	'ebalom',
	'ecchi',
	'een',
	'eikel',
	'ejaculation',
	'el',
	'emmerdant',
	'emmerder',
	'emmerdeur',
	'emmerdeuse',
	'en',
	'enculé',
	'enculée',
	'enculee',	// Mother-fucker (feminine)
	'enculée',	// Mother-fucker (feminine)
	'encule',	// Mother-fucker (masculine)
	'enculé',	// Mother-fucker (masculine)
	'enculer',	// To fuck in the ass
	'enculeur',
	'enculeurs',
	'enfoiré',
	'enfoire',	// Bastard (masculine)
	'enfoiré',	// Bastard (masculine)
	'enfoirée',
	'engerd',
	'ereksjon',
	'erotic',
	'erotism',
	'escort',
	'Esperma',
	'esporra',
	'esterin',
	'étron',
	'etterbak', 	// Annoying person (mostly children)
	'eunuch',
	'f0ck',
	'faen',
	'fæn',
	'fag',
	'faggot',
	'fags',
	'fan',
	'fanculo',
	'fanden',
	'fanny',
	'fare',
	'fare unaŠ',
	'fart',
	'fasz',
	'faszfej',
	'faszfejek',
	'faszfejeket',
	'faszfejet',
	'faszok',
	'faszokat',
	'faszt',
	'fat',
	'fava',
	'fava',
	'fck',
	'fcker',
	'fckr',
	'fcku',
	'fcuk',
	'fecal',
	'fek',
	'feken',
	'fekfikanto',
	'feklekulo',
	'fekulo',
	'felch',
	'fellatio',
	'ふぇら',     	// Fellatio
	'feltch',
	'female',
	'femdom',
	'femminuccia',
	'femminuccia',
	'fetish',
	'fettbacke',
	'fica',
	'fica',
	'fick',
	'ficken',
	'fiddua',        // cunt (fidd- version); sg. partitive
	'fiddu',         // cunt (fidd- version); interjection, sg. nominative
	'fidduihin',     // cunt (fidd- version); pl. illative
	'fidduilla',     // cunt (fidd- version); pl. adessive
	'fidduille',     // cunt (fidd- version); pl. allative
	'fidduilta',     // cunt (fidd- version); pl. ablative
	'fidduissa',     // cunt (fidd- version); pl. inessive
	'fidduista',     // cunt (fidd- version); pl. elative
	'fidduja',       // cunt (fidd- version); pl. partitive
	'fiddujen',      // cunt (fidd- version); pl. genitive
	'fiddulla',      // cunt (fidd- version); sg. adessive
	'fiddulle',      // cunt (fidd- version); sg. allative
	'fiddulta',      // cunt (fidd- version); sg. ablative
	'fiddun',        // cunt (fidd- version); sg. genitive
	'fiddussa',      // cunt (fidd- version); sg. inessive
	'fiddusta',      // cunt (fidd- version); sg. elative
	'fiddut',        // cunt (fidd- version); pl. nominative
	'fidduun',       // cunt (fidd- version); sg. illative
	'Fiesta',
	'figa',
	'figa',
	'figging',
	'figlio',
	'figlio di buona donna',
	'figlio di puttana',
	'figone',
	'figone',
	'fik',
	'fikado',
	'fikema',
	'fikfek',
	'fiki',
	'fikiĝi',
	'fikiĝu',
	'fikilo',
	'fikklaŭno',
	'fikota',
	'fiku',
	'filho',
	'fille',
	'fils',
	'fing',
	'fingerbang',
	'fingering',
	'fingok',
	'fingokat',
	'fingot',
	'finocchio',
	'finocchio',
	'fion',		// Ass
	'fisse',
	'fissehår',
	'fisting',
	'fitta',
	'fitte',
	'fittetryne',
	'fittig',
	'fittua',        // cunt (f- version); sg. partitive
	'fittu',         // cunt (f- version); interjection, sg. nominative
	'fittuihin',     // cunt (f- version); pl. illative
	'fittuja',       // cunt (f- version); pl. partitive
	'fittujen',      // cunt (f- version); pl. genitive
	'fittuun',       // cunt (f- version); sg. illative
	'fituilla',      // cunt (f- version); pl. adessive
	'fituille',      // cunt (f- version); pl. allative
	'fituilta',      // cunt (f- version); pl. ablative
	'fituissa',      // cunt (f- version); pl. inessive
	'fituista',      // cunt (f- version); pl. elative
	'fitulla',       // cunt (f- version); sg. adessive
	'fitulle',       // cunt (f- version); sg. allative
	'fitulta',       // cunt (f- version); sg. ablative
	'fitun',         // cunt (f- version); sg. genitive
	'fitussa',       // cunt (f- version); sg. inessive
	'fitusta',       // cunt (f- version); sg. elative
	'fitut',         // cunt (f- version); pl. nominative
	'fiut',
	'fiuta',
	'flamoes',
	'flikken',
	'flikker',
	'flikker', 		// Faggot
	'flikker op', 	// Fuck off!
	'flittchen',
	'flundra',
	'fock', 		// Misspelling of 'fuck' (anglicism)
	'foda',
	'foda-se',
	'foder',
	'føkk',
	'føkking',
	'Follador',
	'Follar',
	'follar',	// Fuck
	'folle',
	'follen',	// Go fuck
	'foot',
	'footjob',
	'för',
	'さんごくじん',	// Foreign resident
	'foreskin',
	'forfiki',
	'forfikiĝu',
	'forfiku',
	'forfurzu',
	'forpisi',
	'forpisu',
	'forpult',
	'førpult',
	'førrpult',
	'fottere',
	'fottere',
	'fottersi',
	'fottersi',
	'fotz',
	'fotze',
	'foutre',
	'foutre',	// Cum
	'fracicone',
	'fracicone',
	'franc',
	'francok',
	'francokat',
	'francot',
	'frango',
	'fratze',
	'fregna',
	'fregna',
	'frocio',
	'frocio',
	'froscio',
	'froscio',
	'frotting',
	'fuck',
	'ファック',     	// Fuck
	'fucker',
	'fuckface',
	'fuckin',
	'fucking',
	'fuckr',
	'fucktards',
	'fuct',
	'fudge',
	'fudgepacker',
	'fuk',
	'fuori',
	'fuori come un balcone',
	'furcia',	// Whore
	'furz',
	'furzulo',
	'futanari',
	'g',
	'gaand',
	'gaandfat',
	'gaandmasti',
	'gaandufad',
	'gadverdamme',
	'gag',
	'galbak',
	'gandu',
	'gang',
	'gangbang',
	'gashti',
	'gasti',
	'gat',
	'gay',
	'geci',
	'gecibb',
	'gecik',
	'geciket',
	'gecit',
	'gedoogzone',
	'geil', 		// Horny
	'geilneef',
	'genital',
	'genitalia',
	'genitals',
	'gerbe',
	'gerber',
	'gesodemieter',
	'geven',
	'ghassa',
	'ghasti',
	'ghuy\'cha\'',
	'giant',
	'Gilipichis',
	'Gilipollas',
	'gilipollas',	// Jerk
	'girl',
	'girls',
	'귀두',    	// Glans penis
	'glory hole',
	'gloryhole',
	'gnoinyj',
	'goatcx',
	'goatse',
	'gobshite',
	'god',
	'godammet',
	'godammit',
	'goddammet',
	'goddammit',
	'goddamn',
	'godverdomme',
	'godverju', 	// Short version of 'godverdomme' (goddammit)
	'godver', 		// Short version of 'godverdomme' (goddammit)
	'gokkun',
	'gol',
	'golden',
	'goldone',
	'goldone',
	'gone',
	'goo',
	'goodpoop',
	'gook',
	'goregasm',
	'göt',
	'göte',
	'götler',
	'götlerde',
	'götlerden',
	'götlere',
	'götleri',
	'götlerin',
	'götte',
	'götten',
	'götü',
	'götün',
	'götveren',
	'götverende',
	'götverenden',
	'götverene',
	'götvereni',
	'götverenin',
	'götverenler',
	'götverenlerde',
	'götverenlerden',
	'götverenlere',
	'götverenleri',
	'götverenlerin',
	'gouine',
	'gówno',
	'gozar',
	'graftak',
	'grande',
	'grandes',
	'gras',
	'gratenkutg',
	'gravy',
	'grelho',
	'greppeldel',
	'griet',
	'grilletto',
	'grilletto',
	'grogniasse',
	'grope',
	'group',
	'g-spot',
	'guanto',
	'guanto',
	'guardone',
	'guardone',
	'gueule',
	'guro',
	'guy',
	'gypo',
	'haahka',
	'Hacer',
	'Haciendo',
	'hackfresse',
	'hæstkug',
	'hæstkuk',
	'けとう',     	// Hairy foreigner
	'haista',
	'hajzl',
	'hand',
	'handjob',
	'hands',
	'harami',
	'haramzade',
	'hard',
	'hård',
	'hardcore',
	'hässiä',
	'hatullinen',
	'hawas',
	'heil',
	'hell',
	'helvete',
	'helveteillä',   // hell, pl. adessive
	'helveteille',   // hell, pl. allative
	'helveteiltä',   // hell, pl. ablative
	'helveteissä',   // hell, pl. inessive
	'helveteistä',   // hell, pl. elative
	'helvetillä',    // hell, sg. adessive
	'helvetille',    // hell, sg. allative
	'helvetiltä',    // hell, sg. ablative
	'helvetin',      // hell, sg. genitive
	'helvetissä',    // hell, sg. inessive
	'helvetistä',    // hell, sg. elative
	'helvetisti',
	'helvetit',      // hell, pl. nominative
	'helvette',
	'helvetteihin',  // hell, pl. illative
	'helvettejä',    // hell, pl. partitive
	'helvettiä',     // hell, sg. partitive
	'helvettien',    // hell, pl. genitive
	'helvetti',      // hell, sg. nominative
	'helvettiin',    // hell, sg. illative
	'hentai',
	'her',
	'heroína',
	'Heroína',
	'hestepik',
	'hestkug',
	'hestkuk',
	'het',
	'heterosexual',
	'hevonkuusi',
	'hevonpaska',
	'hevonperse',
	'hevonvittu',
	'hevonvitunperse',
	'Hija',
	'Hijaputa',
	'hijaputa',	// Son of a bitch (feminine)
	'hijda',
	'Hijo',
	'Hijoputa',
	'hijo puta',	// Son of a bitch
	'hijoputa',	// Son of a bitch
	'hijra',
	'hinteillä',     // fag, pl. adessive
	'hinteille',     // fag, pl. allative
	'hinteiltä',     // fag, pl. ablative
	'hinteissä',     // fag, pl. inessive
	'hinteistä',     // fag, pl. elative
	'hintillä',      // fag, sg. adessive
	'hintille',      // fag, sg. allative
	'hintiltä',      // fag, sg. ablative
	'hintin',        // fag, sg. genitive
	'hintissä',      // fag, sg. inessive
	'hintistä',      // fag, sg. elative
	'hintit',        // fag, pl. nominative
	'hinttareiden',  // faggot, pl. genitive
	'hinttareihin',  // faggot, pl. illative
	'hinttareilla',  // faggot, pl. adessive
	'hinttareille',  // faggot, pl. allative
	'hinttareilta',  // faggot, pl. ablative
	'hinttareissa',  // faggot, pl. inessive
	'hinttareista',  // faggot, pl. elative
	'hinttareita',   // faggot, pl. partitive
	'hinttareitten', // faggot, pl. genitive
	'hinttareja',    // faggot, pl. partitive
	'hinttaria',     // faggot, sg. partitive
	'hinttarien',    // faggot, pl. genitive
	'hinttari',      // faggot, sg. nominative
	'hinttariin',    // faggot, sg. illative
	'hinttarilla',   // faggot, sg. adessive
	'hinttarille',   // faggot, sg. allative
	'hinttarilta',   // faggot, sg. ablative
	'hinttarin',     // faggot, sg. genitive
	'hinttarissa',   // faggot, sg. inessive
	'hinttarista',   // faggot, sg. elative
	'hinttarit',     // faggot, pl. nominative
	'hintteihin',    // fag, pl. illative
	'hinttejä',      // fag, pl. partitive
	'hinttiä',       // fag, sg. partitive
	'hinttien',      // fag, pl. genitive
	'hintti',        // fag, sg. nominative
	'hinttiin',      // fag, sg. illative
	'hirnlos',
	'hitler',
	'hitosti',
	'hitto',
	'hoempert',
	'hoer',
	'hoerenbuurt',
	'hoerenloper',
	'hoer', 		// Hooker; whore; harlot
	'hoerig',
	'hoertje', 		// Hooker
	'hol',
	'hole',
	'homem',
	'homo',
	'homoerotic',
	'homoerótico',
	'homofiel', 	// Homophile
	'homosexual',
	'homse',
	'hond',
	'hondjes',
	'honkey',
	'hooker',
	'hora',
	'hore',
	'horny',
	'horoa',         // whore; sg. partitive
	'horoihin',      // whore; pl. illative
	'horoilla',      // whore; pl. adessive
	'horoille',      // whore; pl. allative
	'horoilta',      // whore; pl. ablative
	'horoissa',      // whore; pl. inessive
	'horoista',      // whore; pl. elative
	'horojen',       // whore; pl. genitive
	'horolla',       // whore; sg. adessive
	'horolle',       // whore; sg. allative
	'horolta',       // whore; sg. ablative
	'horon',         // whore; sg. genitive
	'horoon',        // whore; sg. illative
	'horossa',       // whore; sg. inessive
	'horosta',       // whore; sg. elative
	'horot',         // whore; pl. nominative
	'horo',	// whore; interjection, sg. nominative
	'hostia',	// Bastard, shit, to hit
	'hot',
	'hovno',
	'how',
	'hufter',
	'huge',
	'huisdealer',
	'huj',
	'hump',
	'humping',
	'huoraan',       // whore, sg. illative
	'huoraa',        // whore, sg. partitive
	'huoralla',      // whore, sg. adessive
	'huoralle',      // whore, sg. allative
	'huoralta',      // whore, sg. ablative
	'huoran',        // whore, sg. genitive
	'huorassa',      // whore, sg. inessive
	'huorasta',      // whore, sg. elative
	'huorata',
	'huorat',        // whore, pl. nominative
	'huora',         // whore, sg. nominative
	'huoria',        // whore, pl. partitive
	'huorien',       // whore, pl. genitive
	'huoriin',       // whore, pl. illative
	'huorilla',      // whore, pl. adessive
	'huorille',      // whore, pl. allative
	'huorilta',      // whore, pl. ablative
	'huorissa',      // whore, pl. inessive
	'huorista',      // whore, pl. elative
	'huppelkut', 	// Used to insult a woman's perceived shallowness; literally 'skipping cunt'
	'hure',
	'hurensohn',
	'hviting',
	'i',
	'Idiota',
	'il',
	'images',
	'Imbécil',
	'in',
	'incazzarsi',
	'incazzarsi',
	'incest',
	'incoglionirsi',
	'incoglionirsi',
	'inculare',
	'induiken',
	'inferno',
	'infierno',
	'ingoio',
	'ingoio',
	'걸레년',    	// Insult for women
	'intercourse',
	'ische',
	'ja',
	'jack',
	'jacket',
	'jævel',
	'jævla',
	'jail',
	'jailbait',
	'jajco',
	'jajeczko',
	'jajko',
	'jajo',
	'jan',
	'jan-met-de-korte-achternaam',
	'jar',
	'jat',
	'jätkä',
	'jävlar',
	'jebać',
	'jebany',
	'jebat',
	'jelly',
	'jerk',
	'jesussucks',
	'jhant',
	'jhantu',
	'jigaboo',
	'jiggaboo',
	'jiggerboo',
	'Jilipollas',
	'jiz',
	'jizz',
	'jizzum',
	'job',
	'joder',	// Fuck
	'jodete',	// Go fuck yourself
	'jódete',	// Go fuck yourself
	'johny',
	'joputa',	// Abbreviation of 'hijo de puta' (son of a bitch)
	'jouir',
	'jud',
	'jude',
	'juggs',
	'juice',
	'jumalauta',     // goddamnit, interjection
	'juosten',
	'jutku',
	'jutsku',
	'ka',
	'kacen',
	'kack',
	'kackbratze',
	'kacke',
	'kacken',
	'kackwurst',
	'kaco',
	'kacsuĉulo',
	'kaffir',
	'kakker', 		// Person of higher class/wealth (derogatory); literally 'shitter'
	'kak', 		// Shit
	'kaltağa',
	'kaltağı',
	'kaltağın',
	'kaltak',
	'kaltaklar',
	'kaltaklara',
	'kaltaklarda',
	'kaltaklardan',
	'kaltakları',
	'kaltakların',
	'kaltakta',
	'kaltaktan',
	'kamina',
	'kamine',
	'kaminey',
	'kampflesbe',
	'kanake',
	'kananpaska',
	'kanen',
	'kanjar',
	'kanker', 		// Cancer (expletive)
	'kankeren', 	// Bitch (verb)
	'kankerjoch', 	// Cancer kid (insult)
	'kankerlyer', 	// Cancer sufferer (insult; old spelling)
	'Kapullo',
	'kåt',
	'käteen',
	'ke',
	'kettingzeugg',
	'khajoor',
	'khanaa',
	'khuy',
	'ki',
	'kibaszott',
	'kibaszottabb',
	'kicking',
	'kike',
	'kill',
	'ころす',     	// Kill
	'killer',
	'killin',
	'killing',
	'kimme',
	'kinbaku',
	'kinkster',
	'kinky',
	'kjerring',
	'klaarkomen',
	'klerebeer',
	'klerelijer', 	// Asshole; literally 'cholera sufferer'
	'klitoris',
	'klitt',
	'klojo',
	'klojo', 		// Asshole (shorter version of 'klootzak')
	'klooien',
	'klootjesvolk',
	'klootoog',
	'klootzak',
	'klootzak', 	// Asshole; son of a bitch; literally 'ball sack'
	'kloten',
	'knobbing',
	'knockers',
	'knor',
	'knull',
	'knulla',
	'koffer',
	'koiranpaska',
	'kojono',
	'kokot',
	'kokotina',
	'konchik',
	'konfetku',
	'koňomrd',
	'kontg',
	'kontneuken',
	'kötthuvud',
	'köttnacke',
	'krentekakker',
	'ku\'evo',
	'kug',
	'kugost',
	'kuin',
	'kuk',
	'kukene',
	'kuker',
	'kukk',
	'kukklest',
	'kukkost',
	'kukkpeis',
	'kukkskalle',
	'kuklest',
	'kukost',
	'kukpeis',
	'kuksås',
	'kukskalle',
	'kuktryne',
	'kulli',
	'kullinluikaus',
	'kunda',
	'kunt',
	'kuppainen',
	'kúr',
	'kurafi',
	'kurafik',
	'kurafikat',
	'kurafit',
	'kurva',
	'kurvák',
	'kurvákat',
	'kurvát',
	'kurwa',
	'kurwy',
	'kusaista',
	'kuseksia',
	'kusettaa',
	'kusi',
	'kusipää',
	'kusipäähän',    // pisshead, sg. illative
	'kusipäällä',    // pisshead, sg. adessive
	'kusipäälle',    // pisshead, sg. allative
	'kusipäältä',    // pisshead, sg. ablative
	'kusipään',      // pisshead, sg. genitive
	'kusipää',       // pisshead, sg. nominative
	'kusipäässä',    // pisshead, sg. inessive
	'kusipäästä',    // pisshead, sg. elative
	'kusipäätä',     // pisshead, sg. partitive
	'kusipäät',      // pisshead, pl. nominative
	'kusipäihin',    // pisshead, pl. illative
	'kusipäillä',    // pisshead, pl. adessive
	'kusipäille',    // pisshead, pl. allative
	'kusipäiltä',    // pisshead, pl. ablative
	'kusipäissä',    // pisshead, pl. inessive
	'kusipäistä',    // pisshead, pl. elative
	'kusipäitä',     // pisshead, pl. partitive
	'kusipäitten',   // pisshead, pl. genitive
	'kussekryller',
	'kusta',
	'kustu',
	'kut',
	'kutafon',
	'kutas',
	'kut', 		// Fuck (interjection); vagina
	'kutta',
	'kutte',
	'kuttelikkertje',
	'kutti',
	'kuttiya',
	'kwakkieg',
	'kyrpä',
	'kyrpää',        // cock, sg. partitive
	'kyrpään',       // cock, sg. illative
	'kyrpä',         // cock, sg. nominative
	'kyrpänaama',
	'kyrpiä',
	'kyrpiä',        // cock, pl. partitive
	'kyrpien',       // cock, pl. genitive
	'kyrpiin',       // cock, pl. illative
	'kyrpiintyä',
	'kyrpiintynyt',
	'kyrvällä',      // cock, sg. adessive
	'kyrvälle',      // cock, sg. allative
	'kyrvältä',      // cock, sg. ablative
	'kyrvän',        // cock, sg. genitive
	'kyrvässä',      // cock, sg. inessive
	'kyrvästä',      // cock, sg. elative
	'kyrvät',        // cock, pl. nominative
	'kyrvillä',      // cock, pl. adessive
	'kyrville',      // cock, pl. allative
	'kyrviltä',      // cock, pl. ablative
	'kyrvissä',      // cock, pl. inessive
	'kyrvistä',      // cock, pl. elative
	'kyrvitys',
	'la',
	'labia',
	'どかた',     	// Laborer
	'lahtari',
	'Lameculos',
	'l\'arte',
	'l'arte bolognese',
	'le',
	'leather',
	'leccaculo',
	'leccaculo',
	'lecchino',
	'lecchino',
	'legal',
	'leggecibb',
	'legkibaszottabb',
	'legs',
	'legszarabb',
	'lemon',
	'lesbe',
	'lésbica',
	'lesbo',
	'lespe',
	'やらせろ',    	// 'Let me do you'
	'licking',
	'liefdesgrot',
	'lijer', 		// Sufferer (insult); slang spelling of 'lijder'
	'lips',
	'lizać',
	'load',
	'loda',
	'lodu',
	'lofare',
	'lofare',
	'loffa',
	'loffa',
	'loffare',
	'loffare',
	'lolita',
	'lort',
	'love',
	'lovemaking',
	'lovit',
	'ludder',
	'luder',
	'lul',
	'lul-de-behanger',
	'lul', 		// Dick
	'lulhannes',
	'lulhannes', 	// Dickhead
	'lumaca',
	'lumaca',
	'lummel',
	'lümmel',
	'きちがい',     	// Lunatic
	'lund',
	'lundtopi',
	'lundure',
	'lutka',
	'm',
	'maa',
	'maaien',
	'maal',
	'maarli',
	'maarten',
	'Maciza',
	'Macizorra',
	'madar',
	'madonna',
	'madre',
	'mafketel',
	'makakken', 	// Moroccans (racist; plural)
	'makak', 		// Moroccan (racist)
	'make',
	'maken',
	'maldito',
	'male',
	'MALPT',
	'mama',
	'Mamada',
	'mamada',	// Blowjob
	'mamona',	// Sucker (feminine)
	'mamon',	// Sucker
	'mamón',	// Sucker
	'mamrd',
	'man',
	'manico',
	'manico',
	'mannaggia',
	'mannaggia',
	'mano',
	'marha',
	'marhák',
	'marhákat',
	'marhát',
	'Marica',
	'marica',	// Faggy
	'Maricón',
	'maricona',	// Drag queen, lesbian
	'Mariconazo',
	'mariconazo',	// Faggot
	'maricon',	// Faggot
	'maricón',	// Faggot
	'martillo',
	'masturbasjon',
	'masturbate',
	'딸딸이',    	// Masturbation
	'masturbere',
	'matennaaierg',
	'matje',
	'me',
	'megdöglik',
	'mein',
	'men',
	'menage',
	'ménage',
	'merda',
	'merda',
	'merdata',
	'merdata',
	'merde',
	'merde',	// Shit
	'merdeuse',
	'merdeux',
	'merdoso',
	'merdoso',
	'mère',
	'meuf',
	'mierda',
	'Mierda',
	'mignotta',
	'mignotta',
	'mijn',
	'milf',
	'MILF',
	'minchia',
	'minchia',
	'minchione',
	'minchione',
	'miseria',
	'missionary',
	'miststück',
	'mof',
	'mof', 		// German (derogatory)
	'molest',
	'molo',
	'molopää',
	'mona',
	'mona',
	'mongolen', 	// Person with Down syndrome (derogatory; plural)
	'mongool', 		// Person with Down syndrome (derogatory)
	'monta',
	'monta',
	'montare',
	'montare',
	'mooh',
	'moona',
	'moonade',
	'moonar',
	'moonat',
	'moose',
	'möpse',
	'morgenlatte',
	'moron',
	'möse',
	'motherfuck',
	'motherfucker',
	'mound',
	'moyu',
	'mr',
	'mrdat',
	'mrdka',
	'mrdník',
	'mthrfckr',
	'mudack',
	'muff',
	'muffdiving',
	'mufti',
	'mulkero',
	'mulkku',
	'mulkkua',       // dick, sg. partitive
	'mulkku',        // dick, sg. nominative
	'mulkkuihin',    // dick, pl. illative
	'mulkkuja',      // dick, pl. partitive
	'mulkkujen',     // dick, pl. genitive
	'mulkkuun',      // dick, sg. illative
	'mulkuilla',     // dick, pl. adessive
	'mulkuille',     // dick, pl. allative
	'mulkuilta',     // dick, pl. ablative
	'mulkuissa',     // dick, pl. inessive
	'mulkuista',     // dick, pl. elative
	'mulkulla',      // dick, sg. adessive
	'mulkulle',      // dick, sg. allative
	'mulkulta',      // dick, sg. ablative
	'mulkun',        // dick, sg. genitive
	'mulkussa',      // dick, sg. inessive
	'mulkusta',      // dick, sg. elative
	'mulkut',        // dick, pl. nominative
	'mulkvisti',
	'muna',
	'munapää',
	'munaton',
	'muncher',
	'murder',
	'murderer',
	'muschi',
	'mussa',
	'mussa',
	'mutakuono',
	'muterfiker',
	'mutiainen',
	'mutsg',
	'mutta',
	'mutterficker',
	'mutth',
	'my',
	'na',
	'naaien',
	'naakt',
	'nackt',
	'naida',
	'nainti',
	'najayaz',
	'nakryt\'sja',
	'nambla',
	'narttu',
	'narttua',       // bitch, sg. partitive
	'narttu',        // bitch, sg. nominative
	'narttuihin',    // bitch, pl. illative
	'narttuja',      // bitch, pl. partitive
	'narttujen',     // bitch, pl. genitive
	'narttuun',      // bitch, sg. illative
	'nartuilla',     // bitch, pl. adessive
	'nartuille',     // bitch, pl. allative
	'nartuilta',     // bitch, pl. ablative
	'nartuissa',     // bitch, pl. inessive
	'nartuista',     // bitch, pl. elative
	'nartulla',      // bitch, sg. adessive
	'nartulle',      // bitch, sg. allative
	'nartulta',      // bitch, sg. ablative
	'nartun',        // bitch, sg. genitive
	'nartussa',      // bitch, sg. inessive
	'nartusta',      // bitch, sg. elative
	'nartut',        // bitch, pl. nominative
	'nave',
	'nave scuola',
	'nawashi',
	'nazi',
	'Nazi',
	'nazi',		// Nazi
	'nędzy',
	'neekereiden',   // nigger, pl. genitive
	'neekereihin',   // nigger, pl. illative
	'neekereillä',   // nigger, pl. adessive
	'neekereille',   // nigger, pl. allative
	'neekereiltä',   // nigger, pl. ablative
	'neekereissä',   // nigger, pl. inessive
	'neekereistä',   // nigger, pl. elative
	'neekereitä',    // nigger, pl. partitive
	'neekereitten',  // nigger, pl. genitive
	'neekerejä',     // nigger, pl. partitive
	'neekeri',
	'neekeriä',      // nigger, sg. partitive
	'neekerien',     // nigger, pl. genitive
	'neekeriin',     // nigger, sg. illative
	'neekerillä',    // nigger, sg. adessive
	'neekerille',    // nigger, sg. allative
	'neekeriltä',    // nigger, sg. ablative
	'neekeri',       // nigger, sg. nominative
	'neekerin',      // nigger, sg. genitive
	'neekerissä',    // nigger, sg. inessive
	'neekeristä',    // nigger, sg. elative
	'neekerit',      // nigger, pl. nominative
	'neger',
	'neger', 		// Black male (not necessarily considered an insult)
	'negerin', 		// Black female (not necessarily considered an insult)
	'nègre',
	'negre',	// Nigger (masculine)
	'nègre',	// Nigger (masculine)
	'negresse',	// Nigger (feminine)
	'négresse',	// Nigger (feminine)
	'negro',
	'にぐろ',     	// Negro
	'くろんぼ',     	// Negro
	'nekru',
	'neonazi',
	'ner',
	'nerchia',
	'nerchia',
	'neuken',
	'neuken', 		// Fucking
	'neukstier',
	'neuk', 		// (to) fuck
	'nicht',
	'nig',
	'nigga',
	'niggah',
	'nigger',
	'nikker', 		// Nigger
	'nimphomania',
	'nippel',
	'nipple',
	'유두',     	// Nipple
	'nipples',
	'nique',
	'nique',	// Fuck
	'niquer',	// To fuck
	'no',
	'nog',
	'nonce',
	'noune',
	'nsber', 		// NSB member (insult synonymous with traitor)
	'nsb', 		// Nationaal-Socialistische Beweging (National Socialist Movement)
	'nsdap',
	'nsfw',
	'nude',
	'nudity',
	'nudo',
	'nudo',
	'nummertje',
	'nuolla',
	'nussi',
	'nussia',
	'nussija',
	'nussinta',
	'nutsack',
	'nutte',
	'nympho',
	'nymphomania',
	'o',
	'obciągać',
	'octopussy',
	'oetlul',
	'of',
	'off',
	'ojete',	// Anus (slang)
	'olalla',
	'olla',
	'omorashi',
	'on',
	'onanieren',
	'one',
	'op',
	'opgeilen',
	'opizdenet',
	'opkankeren',
	'oprotten',
	'opsodemieteren',
	'opzouten',
	'oral',
	'사까시',     	// Oral sex
	'orgasm',
	'오르',     	// Orgasm
	'orgasmus',
	'orgy',
	'Orina',
	'orospu',
	'orospuda',
	'orospudan',
	'orospular',
	'orospulara',
	'orospularda',
	'orospulardan',
	'orospuları',
	'orospuların',
	'orospunun',
	'orospuya',
	'orospuyu',
	'oslošoust',
	'ostia',	// Abbreviation of 'hostia' (bastard, shit, to hit)
	'osto\'eblo',
	'ostokhuitel\'no',
	'ot\'ebis',
	'otmudohat',
	'otpizdit',
	'otsosi',
	'otuz',
	'ouwe',
	'ouwehoer',
	'ouwehoeren',
	'ouwehoeren', 	// To talk bullshit; literally 'old whores'
	'på',
	'paal',
	'paardekop',
	'paardelul',
	'paardelul', 	// Horsedick
	'packer',
	'padlo',
	'padulo',
	'padulo',
	'paedo',
	'paedophile',
	'pæss',
	'paidaish',
	'paja',
	'pajillero',	// Wanker
	'paki',
	'pakkis',
	'pałę',
	'palen',
	'paljaalla',
	'palle',
	'palle',
	'palli',
	'pallit',
	'palloso',
	'palloso',
	'palm',
	'palucher',
	'paneleiro',
	'paneskella',
	'panettaa',
	'panna',
	'pano',
	'pantava',
	'panties',
	'panty',
	'pariu',
	'partouze',	// Sex orgy
	'party',
	'paska',
	'paskaan',       // shit, sg. illative
	'paskaa',        // shit, sg. partitive
	'paskainen',
	'paskalla',      // shit, sg. adessive
	'paskalle',      // shit, sg. allative
	'paskalta',      // shit, sg. ablative
	'paskamainen',
	'paskanmarjat',
	'paskan',        // shit, sg. genitive
	'paskantaa',
	'paskapää',
	'paskapuhe',
	'paska',         // shit, sg. nominative
	'paskassa',      // shit, sg. inessive
	'paskasta',      // shit, sg. elative
	'paskat',        // shit, pl. nominative
	'paskattaa',
	'paskiainen',
	'paskoa',
	'paskoihin',     // shit, pl. illative
	'paskoilla',     // shit, pl. adessive
	'paskoille',     // shit, pl. allative
	'paskoilta',     // shit, pl. ablative
	'paskoissa',     // shit, pl. inessive
	'paskoista',     // shit, pl. elative
	'paskoja',       // shit, pl. partitive
	'paskojen',      // shit, pl. genitive
	'passar',
	'patacca',
	'patacca',
	'pataka',
	'patakha',
	'patonza',
	'patonza',
	'patte',
	'pau',
	'pd',		// Fag
	'pecker',
	'pecorina',
	'pecorina',
	'pédale',
	'pédé',
	'pede',		// Fag
	'pédé',		// Fag
	'pedik',
	'pedo',
	'Pedo',
	'pedobear',
	'pedofil',
	'pedofile',
	'pedophile',
	'pegging',
	'pehko',
	'peidar',
	'pele',
	'pelék',
	'pen1s',
	'pendon',	// Slob
	'pendón',	// Slob
	'penetration',
	'penis',
	'잠지',     	// Penis
	'ちんこ',     	// Penis
	'페니스',    	// Penis
	'pênis',
	'자지',     	// Penis (slang)
	'penozeg',
	'pentele',
	'perdet',
	'perhanaa',      // deuce, sg. partitive
	'perhanaan',     // deuce, sg. illative
	'perhana',       // deuce, sg. nominative
	'perhanalla',    // deuce, sg. adessive
	'perhanalle',    // deuce, sg. allative
	'perhanalta',    // deuce, sg. ablative
	'perhanan',      // deuce, sg. genitive
	'perhanassa',    // deuce, sg. inessive
	'perhanasta',    // deuce, sg. elative
	'perhanat',      // deuce, pl. nominative
	'perhanoiden',   // deuce, pl. genitive
	'perhanoihin',   // deuce, pl. illative
	'perhanoilla',   // deuce, pl. adessive
	'perhanoille',   // deuce, pl. allative
	'perhanoilta',   // deuce, pl. ablative
	'perhanoissa',   // deuce, pl. inessive
	'perhanoista',   // deuce, pl. elative
	'perhanoita',    // deuce, pl. partitive
	'perhanoitten',  // deuce, pl. genitive
	'perkele',
	'perkele',       // devil, sg. nominative
	'perkeleellä',   // devil, sg. adessive
	'perkeleelle',   // devil, sg. allative
	'perkeleeltä',   // devil, sg. ablative
	'perkeleen',     // devil, sg. genitive
	'perkeleeseen',  // devil, sg. illative
	'perkeleessä',   // devil, sg. inessive
	'perkeleestä',   // devil, sg. elative
	'perkeleesti',
	'perkeleet',     // devil, pl. nominative
	'perkeleiden',   // devil, pl. genitive
	'perkeleihin',   // devil, pl. illative
	'perkeleillä',   // devil, pl. adessive
	'perkeleille',   // devil, pl. allative
	'perkeleiltä',   // devil, pl. ablative
	'perkeleisiin',  // devil, pl. illative
	'perkeleissä',   // devil, pl. inessive
	'perkeleistä',   // devil, pl. elative
	'perkeleitä',    // devil, pl. partitive
	'perkeleitten',  // devil, pl. genitive
	'perkelettä',    // devil, sg. partitive
	'persaukinen',
	'perse',
	'perseääliö',
	'perse',         // ass, sg. nominative
	'perseellä',     // ass, sg. adessive
	'perseelle',     // ass, sg. allative
	'perseeltä',     // ass, sg. ablative
	'perseen',       // ass, sg. genitive
	'perseennuolija',
	'perseeseen',    // ass, sg. illative
	'perseessä',     // ass, sg. inessive
	'perseestä',
	'perseestä',     // ass, sg. elative
	'perseet',
	'perseet',       // ass, pl. nominative
	'perseiden',     // ass, pl. genitive
	'perseihin',     // ass, pl. illative
	'perseillä',     // ass, pl. adessive
	'perseille',     // ass, pl. allative
	'perseiltä',     // ass, pl. ablative
	'perseisiin',    // ass, pl. illative
	'perseissä',     // ass, pl. inessive
	'perseistä',     // ass, pl. elative
	'perseitä',      // ass, pl. partitive
	'perseitten',    // ass, pl. genitive
	'persereikä',
	'persettä',
	'persettä',      // ass, sg. partitive
	'persläpi',
	'perspano',
	'persvako',
	'Pervertido',
	'pesce',
	'pesce',
	'pess',
	'petasse',	// Slut/Show-off (feminine)
	'pétasse',	// Slut/Show-off (feminine)
	'péter',
	'petuh',
	'Pezón',
	'phone',
	'phuk',
	'piča',
	'piče',
	'piĉen',
	'picha',	// Dick
	'píchat',
	'picio',
	'picio',
	'piĉo',
	'picsa',
	'picsákat',
	'picsát',
	'píčus',
	'pidar',
	'piece',
	'pieprzyć',
	'piercing',
	'pierdoła',
	'pierdolę',
	'pierdolec',
	'pierdolić',
	'pierdolnięty',
	'pierdzieć',
	'piesen',
	'pig',
	'pijp',
	'pijpbekkieg',
	'pijpen',
	'pik',
	'pikhår',
	'pikk',
	'pik', 		// Penis
	'pikslugeri',
	'piksutteri',
	'pilkunnussija',
	'pillows',
	'pillu',
	'pillua',        // pussy, sg. partitive
	'pilluihin',     // pussy, pl. illative
	'pilluilla',     // pussy, pl. adessive
	'pilluille',     // pussy, pl. allative
	'pilluilta',     // pussy, pl. ablative
	'pilluissa',     // pussy, pl. inessive
	'pilluista',     // pussy, pl. elative
	'pilluja',       // pussy, pl. partitive
	'pillujen',      // pussy, pl. genitive
	'pillulla',      // pussy, sg. adessive
	'pillulle',      // pussy, sg. allative
	'pillulta',      // pussy, sg. ablative
	'pillun',        // pussy, sg. genitive
	'pillu',         // pussy, sg. nominative
	'pillussa',      // pussy, sg. inessive
	'pillusta',      // pussy, sg. elative
	'pillut',
	'pillut',        // pussy, pl. nominative
	'pilluun',       // pussy, sg. illative
	'pimmel',
	'pimp',
	'pimpern',
	'pina',
	'pinák',
	'pinákat',
	'pinát',
	'pincare',
	'pincare',
	'Pinche',
	'pine',		// Dick
	'pinkeln',
	'pinto',
	'pipa',
	'pipa',
	'pipari',
	'pipeline',
	'pipi',
	'pipì',
	'pipì',
	'pippa',
	'pippone',
	'pippone',
	'pirla',
	'pirla',
	'piru',
	'pis',
	'Pis',
	'pisciare',
	'pisciare',
	'piscio',
	'piscio',
	'pisello',
	'pisello',
	'piss',
	'pissen',
	'pisser',
	'pissing',
	'pisspig',
	'pistää',
	'pistola',
	'pistola',
	'pistolotto',
	'pistolotto',
	'pitt',
	'pizda',
	'pizdato',
	'pizdatyi',
	'piz\'det',
	'pizdetc',
	'pizdoi',
	'pizdopro\'ebina',
	'pizdoproyob',
	'pizdu',
	'pizd\'uk',
	'pizdy',
	'piz`dyulina',
	'play',
	'playboy',
	'pleasure',
	'pleurislaaier',
	'pleuris', 		// Pleuritis (expletive), slang for tuberculosis
	'po',
	'pocket',
	'pöcs',
	'pöcsök',
	'pöcsöket',
	'pöcsöt',
	'podi',
	'poeben',
	'poep',
	'poepen',
	'poepen', 		// Pooping
	'poep', 		// Poop
	'pofa',
	'pofákat',
	'pofát',
	'po\'imat\'',
	'po\'iti',
	'pojeb',
	'pök',
	'pøke',
	'pokkelijer', 	// Asshole; slang meaning 'smallpox sufferer'
	'pokkelyer', 	// Asshole; slang meaning 'smallpox sufferer', old spelling
	'pokkenlyer', 	// Asshole; slang meaning 'smallpox sufferer', old spelling
	'pokken', 		// Smallpox
	'pokker',
	'pokke', 		// Smallpox; slang spelling of 'pokken'
	'pole',
	'polla',	// Dick
	'pollon',	// Dick
	'pollón',	// Dick
	'poluchit',
	'polvo',	// To ejaculate
	'pomiciare',
	'pomiciare',
	'pompa',
	'pompa',
	'pompinara',
	'pompino',
	'pompino',
	'pong',
	'ponyplay',
	'poof',
	'poon',
	'poontang',
	'poop',
	'poopchute',
	'poot',
	'popel',
	'popierdolony',
	'poppen',
	'porca',
	'porca',
	'porca madonna',
	'porca miseria',
	'porca puttana',
	'porco',
	'porco dio',
	'porco due',
	'porco zio',
	'porn',
	'porno',
	'pornography',
	'porra',
	'portiekslet',
	'position',
	'pososi',
	'posrat',
	'pot',
	'potorro',	// Vagina
	'potta',
	'potta',
	'potverdorie',
	'pouffe',	// Show-off (feminine)
	'pouffiasse',
	'pouffiasse',	// Show-off (feminine)
	'pousse-crotte',
	'power',
	'prawda',
	'prcat',
	'prdel',
	'prdele',
	'prdelka',
	'prenditi',
	'prick',
	'prince',
	'prissat',
	'proebat',
	'promudobl\'adsksya',
	'pron',
	'propezdoloch',
	'prosrat',
	'prostituée',
	'Prostituta',
	'prostitute',
	'창녀',     	// Prostitute
	'prutt',
	'pthc',
	'pubes',
	'いんもう',     	// Pubic hair
	'publiciteitsgeil',
	'pujari',
	'pul',
	'pule',
	'pult',
	'punani',
	'punany',
	'punch',
	'punci',
	'puncik',
	'pung',
	'pupp',
	'puppami',
	'puppami',
	'pussy',
	'puta',
	'Puta',
	'puta',		// Bitch/whore
	'putain',
	'putain',	// Slut
	'pute',
	'pute',		// Slut
	'puto',		// Bitch/whore (masculine), faggot
	'puton',	// Bitch/whore
	'putón',	// Bitch/whore
	'puttana',
	'puttana',
	'pyllyvako',
	'QI\'yaH',
	'quaglia',
	'quaglia',
	'que',
	'queaf',
	'queca',
	'queef',
	'queer',
	'quim',
	'quisling',
	'Qu\'vatlham',
	'raam',
	'raand',
	'raaskallen',
	'rabo',
	'race',
	'Racista',
	'ræv',
	'ræva',
	'rævhøl',
	'rævtryne',
	'rævva',
	'raghead',
	'raging',
	'raio',
	'Ramera',
	'ramoner',
	'randi',
	'rape',
	'강간',     	// Rape
	'れいぷ',     	// Rape
	'ごうかん',     	// Rape
	'りょうじょく', 	// Rape
	'raped',
	'rapes',
	'raping',
	'rapist',
	'raspeezdeyi',
	'raspizdatyi',
	'rass',
	'rasshøl',
	'rasstryne',
	'rättipää',
	'rautryne',
	'raz\'yebuy',
	'raz\'yoba',
	'recchione',
	'recchione',
	'rectal',
	'rectum',
	'reet',
	'reetridder',
	'regina',
	'regina',
	'reikä',
	'remsporeng',
	'restraint',
	'병신',    	// Retard
	'reudig',
	'reutelen',
	'reva',
	'reverse',
	'ricchione',
	'rimjob',
	'rimming',
	'rincoglionire',
	'rincoglionire',
	'ripsipiirakka',
	'rizzarsi',
	'rizzarsi',
	'robic',
	'robić',
	'roetmop', 		// Nigger; literally 'soot mop'
	'rompe',
	'rompiballe',
	'rompiballe',
	'ronk',
	'rosebuds',
	'rosette',
	'rosy',
	'rothoer',
	'rottinculo',
	'rotzak',
	'rotzak', 		// Scumbag
	'röv',
	'røv',
	'rövhål',
	'røvhul',
	'rövknulla',
	'røvskæg',
	'røvspræke',
	'ruchać',
	'ruffiano',
	'ruffiano',
	'rukhond',
	'rukken',
	'rukker',
	'runk',
	'runka',
	'runkata',
	'runkkari',
	'runkkaus',
	'runkku',
	'rusty',
	'ryssä',
	'rzygać',
	's',
	'saala',
	'saali',
	'saamareiden',   // bloody, pl. genitive
	'saamareihin',   // bloody, pl. illative
	'saamareilla',   // bloody, pl. adessive
	'saamareille',   // bloody, pl. allative
	'saamareilta',   // bloody, pl. ablative
	'saamareissa',   // bloody, pl. inessive
	'saamareista',   // bloody, pl. elative
	'saamareita',    // bloody, pl. partitive
	'saamareitten',  // bloody, pl. genitive
	'saamareja',     // bloody, pl. partitive
	'saamaria',      // bloody, sg. partitive
	'saamari',       // bloody, sg. nominative
	'saamarien',     // bloody, pl. genitive
	'saamariin',     // bloody, sg. illative
	'saamarilla',    // bloody, sg. adessive
	'saamarille',    // bloody, sg. allative
	'saamarilta',    // bloody, sg. ablative
	'saamarin',      // bloody, sg. genitive
	'saamarissa',    // bloody, sg. inessive
	'saamarista',    // bloody, sg. elative
	'saamarit',      // bloody, pl. nominative
	'saatanaan',     // satan, sg. illative
	'saatanaa',      // satan, sg. partitive
	'saatanalla',    // satan, sg. adessive
	'saatanalle',    // satan, sg. allative
	'saatanalta',    // satan, sg. ablative
	'saatanan',      // satan, sg. genitive
	'saatana',       // satan, sg. nominative
	'saatanassa',    // satan, sg. inessive
	'saatanasta',    // satan, sg. elative
	'saatanasti',
	'saatanat',      // satan, pl. nominative
	'saatanoiden',   // satan, pl. genitive
	'saatanoihin',   // satan, pl. illative
	'saatanoilla',   // satan, pl. adessive
	'saatanoille',   // satan, pl. allative
	'saatanoilta',   // satan, pl. ablative
	'saatanoissa',   // satan, pl. inessive
	'saatanoista',   // satan, pl. elative
	'saatanoita',    // satan, pl. partitive
	'saatanoitten',  // satan, pl. genitive
	'sac',
	'sacanagem',
	'sack',
	'sackgesicht',
	'saco',
	'Sádico',
	'sadism',
	'sæd',
	'saksocu',
	'saksocuda',
	'saksocudan',
	'saksocular',
	'saksoculara',
	'saksocularda',
	'saksoculardan',
	'saksocuları',
	'saksocuların',
	'saksocunun',
	'saksocuya',
	'saksocuyu',
	'salaud',
	'salaud',	// Bastard/backstabber (masculine)
	'salchichas',
	'salopard',	// Bastard/backstabber (masculine)
	'salop',	// Bastard/backstabber (masculine)
	'salope',
	'salope',	// Slut (feminine)
	'빠굴이',    	// Same pronunciation as slang for sexual relationship
	'부랄',    	// Same pronunciation as the word for testicles
	'sanchez',
	'santorum',
	'sås',
	'satan',
	'sätta',
	'sattan',
	'sau',
	'sbattere',
	'sbattere',
	'sbattersi',
	'sbattersi',
	'sborra',
	'sborra',
	'sborrata',
	'sborrata',
	'sborrone',
	'sborrone',
	'sbrodolata',
	'sbrodolata',
	'scat',
	'schabracke',
	'schatje',
	'scheise',
	'scheisse',
	'scheiße',
	'scheissen',
	'scheisser',
	'scheißhaus',
	'sch\'elkat',
	'schiaffi',
	'schiesser',
	'schijt',
	'schijten',
	'schise',
	'schlampe',
	'schlong',
	'schnackeln',
	'schoft',
	'schuinsmarcheerder',
	'schwanz',
	'schwanzlutscher',
	'schweinepriester',
	'schwuchtel',
	'schwul',
	'schwuler',
	'scissoring',
	'scopare',
	'scopare',
	'scopata',
	'scopata',
	'scorreggiare',
	'scorreggiare',
	'screw',
	'scrotum',
	'scuola',
	's\'ebat\'sya',
	'sega',
	'sega',
	'segaiolo',
	'segg',
	'seggek',
	'seggeket',
	'segget',
	'seggfej',
	'seggfejek',
	'seggfejeket',
	'seggfejet',
	'seks', 		// Sex
	'semen',
	'정액',     	// Semen
	'せいえき',     	// Semen
	'Semen',
	'sex',
	'섹스',     	// Sex
	'せっくす',    	// Sex
	'sexo',
	'Sexo',
	'성행위',     	// Sexual act
	'냕성폭행',     	// Sexual assult
	'あいえき',     	// Sexual fluids
	'성관계',     	// Sexual relationship
	'빠구리',    	// Sexual relationship (slang)
	'sexy',
	'shag',
	'shalava',
	'shaved',
	'shemale',
	'shibari',
	'shit',
	'씨발',     	// Shit
	'うんこ',     	// Shit
	'shitblimp',
	'shite',
	'shitty',
	'shiz',
	'shota',
	'shower',
	'showers',
	'shrimping',
	'sıçmak',
	'sik',
	'sike',
	'siker',
	'siki',
	'sikilir',
	'sikilmez',
	'sikin',
	'sikler',
	'siklerde',
	'siklerden',
	'siklere',
	'sikleri',
	'siklerin',
	'sikmek',
	'sikmemek',
	'sikmez',
	'sikte',
	'sikten',
	'siktir',
	'siktirir',
	'siktirmez',
	'sisters',
	'skäggbiff',
	'skeet',
	'skinkerytter',
	'skit',
	'skita',
	'skurwysyn',
	'slag',
	'slanteye',
	'とさつ',     	// Slaughter
	'slempen',
	'sletg',
	'slet', 		// Slut
	'sletterig',
	'slik',
	'slinguare',
	'slinguare',
	'slinguata',
	'slinguata',
	'sloerie', 		// Slut
	'slut',
	'いんぱい',     	// Slut
	'やりまん',    	// Slut
	's&m',
	'sm',
	'smandrappata',
	'smandrappata',
	'smoker',
	'smut',
	'sm女王',
	'snatch',
	'snedfitta',
	'snefitta',
	'snolg',
	'snol', 		// Moll; prostitute
	'snowballing',
	'soccia',
	'soccia',
	'socmel',
	'socmel',
	'sodemieter',
	'sodom',
	'sodomie',	// Sodomy
	'sodomize',
	'sodomy',
	'개새끼',     	// Son of a bitch
	'soper',
	'Soplagaitas',
	'Soplapollas',
	'sorca',
	'sorca',
	'sotrør',
	'šoustat',
	'spagnola',
	'spagnola',
	'spastic',
	'spaz',
	'どもり',     	// Speech impediment
	'spelen',
	'sperm',
	'spic',
	'spick',
	'spleetoog', 	// Oriental person (derogatory); literally 'slit eye'
	'splooge',
	'spompinare',
	'spompinare',
	'spoo',
	'spooge',
	'spread',
	'spuiten',
	'spunk',
	'squirting',
	'srać',
	'sračka',
	'sraczka',
	'srát',
	'stake',
	'standje',
	'standje-69g',
	'ståpikk',
	'ståpikkene',
	'ståpikker',
	'starfish',
	'steamer',
	'sticchio',
	'sticchio',
	'stivas',
	'stiven',
	'stoephoer',
	'stoephoer', 	// Sidewalk whore
	'stootje',
	'straight',
	'strap',
	'strapon',
	'strappado',
	'stricher',
	'strip',
	'stripper',
	'strontg',
	'stront', 		// Shit; poop; turd
	'stronza',
	'stronza',
	'stronzata',
	'stronzata',
	'stronzo',
	'stronzo',
	'styervo',
	'style',
	'suar',
	'subba',
	'succhiami',
	'succhiami',
	'suce',
	'sucer',	// To suck
	'suck',
	'sucking',
	'sucks',
	'sufferdg',
	'suicide',
	'suka',
	'sukin',
	'sukkel', 		// Softy, dolt, someone you feel sorry for
	'suklaaosasto',
	'šulin',
	'sultry',
	'sveltina',
	'sveltina',
	'sverginare',
	'sverginare',
	'svodit',
	'svoloch',
	'swastika',
	'swinger',
	'syf',
	'syn',
	'szajha',
	'szajhák',
	'szajhákat',
	'szajhát',
	'szar',
	'szarabb',
	'szarik',
	'szarok',
	'szarokat',
	'szart',
	'ta',
	'taint',
	'tainted',
	'tapette',
	'tapette',	// Fag
	'tapijtnek',
	'tare',		// Insane
	'taré',		// Insane
	'tart',
	'tarzanello',
	'tarzanello',
	'taşağa',
	'taşağı',
	'taşağın',
	'taşak',
	'taşaklar',
	'taşaklara',
	'taşaklarda',
	'taşaklardan',
	'taşakları',
	'taşakların',
	'taşakta',
	'taşaktan',
	'taste',
	'tatte',
	'tatti',
	'tavara',
	'te',
	'tea',
	'teefg',
	'temeier',
	'teri',
	'teringlijer',
	'teringlyer', 	// Asshole; slang meaning 'tuberculosis sufferer'
	'tering', 		// Slang for tuberculosis; short for 'vertering' (digestion)
	'terrone',
	'terrone',
	'terrorist',
	'testa',
	'testa di cazzo',
	'불알',    	// Testicles
	'Tetas',
	'tette',
	'tette',
	'teuf',
	'tharak',
	'tharki',
	'threesome',
	'throat',
	'throating',
	'Tía',
	'tied',
	'tiet', 		// Boob; tit
	'tieten', 		// Boobies; titties
	'tietjes', 		// Boobies; titties
	'tight',
	'tirare',
	'tirare',
	'tit',
	'tits',
	'tittchen',
	'titten',
	'titties',
	'titty',
	'tittyfuck',
	'to',
	'toe',
	'toeter',
	'핥아',    	// To lick
	'tomar',
	'tongue',
	'tongzoeng',
	'toosa',
	'top',
	'topa',
	'topa',
	'topless',
	'torneira',
	'tortillera',	// Lesbian
	'tosser',
	'빨아',    	// To suck
	'towelhead',
	'trakhat\'sya',
	'tranny',
	'transar',
	'trappen,',
	'Travesti',
	'tribadism',
	'trimandoblydskiy',
	'tringler',
	'Trio',
	'triootjeg',
	'trique',
	'troia',
	'troia',
	'troietta',
	'troiona',
	'troione',
	'trois',
	'trombare',
	'trombare',
	'trombone',
	'trottel',
	'trottoir',
	'trottoirteef',
	'trou',
	'trut', 		// Bitch
	'tu',
	'tub',
	'tubgirl',
	'tuhkaluukku',
	'tumputtaa',
	'turd',
	'turlute',
	'turpasauna',
	'tusan',
	'tushy',
	'tussu',
	'tussukka',
	'tussut',
	'twat',
	'twink',
	'twinkie',
	'two',
	'tyfuslijer', 	// Asshole; slang meaning 'typhoid fever sufferer'
	'tyfuslyer', 	// Asshole; slang meaning 'typhoid fever sufferer', old spelling
	'tyfus', 		// Typhoid fever
	'염병',		// Typhoid fever (slang)
	'ubl\'yudok',
	'uboy',
	'uccello',
	'uccello',
	'u\'ebitsche',
	'uitgaan',
	'uitlaten',
	'um',
	'un',
	'una',
	'unaŠ',
	'undressing',
	'up',
	'upskirt',
	'urethra',
	'urophilia',
	'utpult',
	'v',
	'vacca',
	'vacca',
	'vaffanculo',
	'vaffanculo',
	'vafl\'a',
	'vafli',
	'vag',
	'vagina',
	'おめこ',     	// Vagina
	'おまんこ',     	// Vagina
	'vaginal',
	'vagin',	// Vagina
	'vai',
	'vai-te',
	'vakipano',
	'van',
	'vangare',
	'vangare',
	'vas',
	'veado',
	'venire',
	'venire',
	'venus',
	'verdomme', 	// Damn it
	'Verga',
	'vergallen',
	'verkloten',
	'verneuken',
	'vetää',
	'vete',
	'vetzak', 		// Fatass
	'veuve',
	'vibe',
	'vibrador',
	'vibrator',
	'viespeuk',
	'viiksi',
	'vingeren',
	'violet',
	'vittu',
	'vittua',        // cunt, sg. partitive
	'vittu',         // cunt, interjection, sg. nominative
	'vittuihin',     // cunt, pl. illative
	'vittuilla',
	'vittuilu',
	'vittuja',       // cunt, pl. partitive
	'vittujen',      // cunt, pl. genitive
	'vittumainen',
	'vittuun',       // cunt, sg. illative
	'vittuuntua',
	'vittuuntunut',
	'vituilla',      // cunt, pl. adessive
	'vituille',      // cunt, pl. allative
	'vituilta',      // cunt, pl. ablative
	'vituissa',      // cunt, pl. inessive
	'vituista',      // cunt, pl. elative
	'vitulla',       // cunt, sg. adessive
	'vitulle',       // cunt, sg. allative
	'vitulta',       // cunt, sg. ablative
	'vitun',
	'vitun',         // cunt, sg. genitive
	'vitussa',       // cunt, sg. inessive
	'vitusta',       // cunt, sg. elative
	'vitusti',
	'vitut',         // cunt, pl. nominative
	'vituttaa',
	'vitutus',
	'vleesroos',
	'vögeln',
	'voldta',
	'vollpfosten',
	'voor',
	'vorarephilia',
	'voyeur',
	'vulva',
	'보지',    	// Vulva
	'Vulva',
	'vyperdysh',
	'vypíčenec',
	'vzdrochennyi',
	'waffle',
	'wand',
	'wank',
	'wanker',
	'watje',
	'weed',
	'welzijnsmafia',
	'wet',
	'wetback',
	'white',
	'whor',
	'whore',
	'wichse',
	'wichsen',
	'wichser',
	'wijf',
	'wild',
	'wip',
	'wippen',
	'wixen',
	'wixer',
	'wkurwiać',
	'wog',
	'women',
	'wonen',
	'wrapping',
	'wrinkled',
	'wtf',
	'wuftje',
	'xana',
	'xochota',
	'xx',
	'xxx',
	'yaoi',
	'yarağa',
	'yarağı',
	'yarağın',
	'yarak',
	'yaraklar',
	'yaraklara',
	'yaraklarda',
	'yaraklardan',
	'yarakları',
	'yarakların',
	'yarakta',
	'yaraktan',
	'yeb',
	'yellow',
	'yiffy',
	'your',
	'zaad',
	'zaadje',
	'za\'ebat',
	'zaebis',
	'zajebisty',
	'zakkenwasser',
	'zakkewassr', 	// Idiot; 'zakkenwasser' shortened to character limit; literally 'jute sack washer'
	'zalupa',
	'zalupat',
	'zamenfekAsesinato',
	'zasranetc',
	'zassat',
	'zeiken',
	'zeiker',
	'zigounette',
	'zijn',
	'zinne',
	'zinne',
	'zio',
	'zio cantante',
	'zitten',
	'zizi',
	'zkurvit',
	'zkurvysyn',
	'zlo\'ebuchy',
	'zmrd',
	'z\'n',
	'zoccola',
	'zoophilia',
	'zorron',	// To be/act slutty
	'žrát',
	'zuigen',
	'zuiplap',
	'آب',
	'آبتو',
	'ابتو',
    	'آب کیر',
	'اب کیر',
	'احتلام',
    	'ارگاسم',
	'ارگاسم',
	'اغتصاب',
	'الکسیز',
	'الکسیس',
	'انگشت کردن',
	'بخطا',
    	'برهنه',
	'برهنه',
	'بز',
	'بزاز',
	'بظر',
	'بگا',
	'به خطا',
	'بوس کیر',
	'بوس کس',
	'بوس کوس',
	'بيضان',
	'پرن',
	'پرنو',
	'پستان',
	'پستون',
	'پشم ک',
    	'پورن',
	'پورن',
    	'پورنو',
	'پورنو',
    	'تجاوز',
	'تجاوز',
    	'تخمی',
	'تخمی',
	'تمص',
	'ثدي',
	'جاکش',
	'جغی',
    	'جق',
    	'جقی',
	'جق',
	'جقی',
    	'جلق',
	'جلق',
	'جماع',
    	'جنده',
	'جنده',
    	'چوچول',
	'چوچول',
    	'حشر',
	'حشر',
	'حشری',
	'حلمة',
	'حیوانیت',
	'حیوونی',
	'خارپاره',
	'خایه',
	'خنثي',
	'خوردن کیر',
	'خول',
	'خونه خالی',
	'دادن',
	'داف',
	'دهنی',
	'دوپر',
	'دودول',
	'دومبول',
	'رژیم ا',
	'رژیم ج',
	'رژیم ط',
	'زب',
	'زدن',
	'زنا',
	'زن قهوه',
	'زن قوه',
	'ساک',
	'ساک زدن',
	'سحاق',
	'سحاقية',
	'سر کیر',
	'سرکیر',
	'سقط جنین',
	'سكس',
	'سکس',
	'سکسی',
	'سکسچت',
	'سکس حیوانات',
	'سوپر',
    	'سوپر ایرانی',
	'سوراخ ک',
	'سولاخ ک',
	'شاذ',
	'شاهین نجفی',
	'شرج',
	'شرموطة',
	'شغ',
	'شغ درد',
	'شق',
	'شمبول',
	'شهوة',
	'شهوت',
	'شهوتی',
	'شورت',
	'شومبول',
	'شونبول',
	'طيز',
	'عاهرة',
	'عرص',
	'فاحشه',
	'فاک',
	'فیر',
	'فرج',
	'فیلم',
	'قتل',
	'قحبة',
	'قحبه',
	'قضيب',
	'قهبه',
	'كس',
    	'کیری',
	'کیر',
	'کیری',
	'کیربوس',
	'کیرخر',
	'کردن',
	'کس',
	'کسبوس',
	'کس تپل',
	'کسته',
    	'کس توپول',
	'کسده',
    	'کس کرد',
	'کس کش',
	'کسکش',
	'کسکشه',
	'کسه',
	'کله ی کیر',
	'کله کیر',
	'کوس',
	'کوس بوس',
	'کون',
	'کونی',
    	'کون کرد',
	'کون کش',
	'کونکش',
	'گایید',
	'گاید',
	'گاییدن',
	'گوز',
	'گوزو',
	'لاپا',
	'لاپایی',
	'لاشی',
	'لبات',
	'لب گرفت',
	'لبوةbordel',
	'لحس',
	'لخت',
	'لختی',
	'لخط',
	'لزبین',
	'لیسی',
	'لش',
	'لعق',
	'لوات',
	'لواط',
	'لوطي',
	'مبادل',
	'متناك',
	'متناكة',
	'مص',
	'مفلقسة',
	'مقعد',
	'ممه',
	'منی',
	'نجفی شاهین',
	'ن لب',
	'نيك',
	'هرزه',
	'همجنس گرا',
	'وحشیانه',
	'бардак',
	'бздёнок',
	'блядки',
	'блядовать',
	'блядство',
	'блядь',
	'бугор',
	'в',
	'валяй',
	'ваньку',
	'вертеть',
	'во',
	'встать',
	'выёбываться',
	'гандон',
	'говно',
	'говнюк',
	'голый',
	'гонять',
	'груши',
	'дать',
	'два',
	'дерьмо',
	'дразнится',
	'дрочит',
	'дрочить',
	'другой',
	'ебать',
	'ебать-копать',
	'ебет',
	'ебётся',
	'ебло',
	'ебнуть',
	'ёб',
	'ёбарь',
	'жопа',
	'жополиз',
	'за',
	'играть',
	'измудохать',
	'каждый',
	'как',
	'какая',
	'кожаной',
	'кулаке',
	'курите',
	'лысого',
	'малофя',
	'манда',
	'мандавошка',
	'мать',
	'мент',
	'мне',
	'можно',
	'мою',
	'муда',
	'мудило',
	'мудозмон',
	'на',
	'наебать',
	'наебениться',
	'наебнуться',
	'нахуячиться',
	'не',
	'невебенный',
	'ней',
	'ни',
	'ним',
	'обнаженный',
	'обоссать',
	'обоссаться',
	'один',
	'околачивать',
	'он',
	'опесдол',
	'офигеть',
	'охуеть',
	'охуйтельно',
	'пальца',
	'пизду',
	'пизды',
	'пинать',
	'половое',
	'разница',
	'раком',
	'с',
	'секс',
	'сиски',
	'сношение',
	'собачу',
	'спиздить',
	'срать',
	'ссать',
	'страдать',
	'твою',
	'траxать',
	'трубку',
	'ты',
	'фиг',
	'фига',
	'флейте',
	'хапать',
	'хер',
	'хохол',
	'хочет',
	'хрен',
	'хуем',
	'хуеплет',
	'хуёво',
	'хуёвый',
	'хуило',
	'хуиней',
	'хуиня',
	'хуй',
	'хуйнуть',
	'хую',
	'хуя',
	'三级片',
	'下三烂',
	'下贱',
	'両刀',
	'両性',
	'両性具有',
	'个老子的',
	'スカートの中',
	'中出し',
	'九游',
	'乱交',
	'乳',
	'乳交',
	'乳头',
	'乳房',
	'乳波臀浪',
	'乳首',
	'二穴',
	'交配',
	'ユダヤ人',
	'人妻',
	'人種',
	'仆街',
	'他奶奶',
	'他奶奶的',
	'他奶娘的',
	'他妈',
	'他妈地',
	'他妈ㄉ王八蛋',
	'他妈的',
	'他娘',
	'他马的',
	'代',
	'你个傻比',
	'你他马的',
	'你全家',
	'你奶奶的',
	'你她马的',
	'你妈',
	'你妈的',
	'你娘',
	'你娘卡好',
	'你娘咧',
	'你它妈的',
	'你它马的',
	'你是鸡',
	'你是鸭',
	'你马的',
	'做爱',
	'傻比',
	'傻逼',
	'児童性虐待',
	'册那',
	'军妓',
	'几八',
	'几叭',
	'几巴',
	'几芭',
	'刚度',
	'刚瘪三',
	'剃毛',
	'ストリップ劇場',
	'勃起する',
	'包皮',
	'十三点',
	'卍',
	'卖B',
	'卖比',
	'卖淫',
	'卵',
	'卵子',
	'双峰微颤',
	'口交',
	'口肯',
	'叫床',
	'吃屎',
	'合意の性交',
	'后庭',
	'吹箫',
	'噴出',
	'塞你公',
	'塞你娘',
	'塞你母',
	'塞你爸',
	'塞你老师',
	'塞你老母',
	'売春婦',
	'处女',
	'変態',
	'外阴',
	'夢精',
	'大卵子',
	'大卵泡',
	'大陰唇',
	'大鸡巴',
	'アジアのかわいい女の子',
	'女の子',
	'女子高生',
	'女王様',
	'女装',
	'奴隷',
	'奶',
	'奶奶的熊',
	'奶子',
	'奸',
	'奸你',
	'她妈地',
	'她妈的',
	'她马的',
	'妈B',
	'妈个B',
	'妈个比',
	'妈个老比',
	'妈妈的',
	'妈比',
	'妈的',
	'妈的B',
	'妈逼',
	'妓',
	'妓女',
	'妓院',
	'妳她妈的',
	'妳妈的',
	'妳娘的',
	'妳老母的',
	'妳马的',
	'姘头',
	'姣西',
	'姦',
	'娘个比',
	'娘的',
	'婊子',
	'婊子养的',
	'嫌い',
	'嫖娼',
	'嫖客',
	'它妈地',
	'它妈的',
	'宦官',
	'密洞',
	'射你',
	'射精',
	'小乳头',
	'小卵子',
	'小卵泡',
	'小瘪三',
	'小肉粒',
	'小骚比',
	'小骚货',
	'小鸡巴',
	'小鸡鸡',
	'お尻',
	'尿道プレイ',
	'屁眼',
	'屁股',
	'屄',
	'屌',
	'巨乳',
	'巨根',
	'干x娘',
	'干七八',
	'干你',
	'干你妈',
	'干你娘',
	'干你老母',
	'干你良',
	'干妳妈',
	'干妳娘',
	'干妳老母',
	'干妳马',
	'干您娘',
	'干机掰',
	'干死CS',
	'干死GM',
	'干死你',
	'干死客服',
	'平手打ち',
	'幹',
	'幼児',
	'幼児性愛者',
	'強姦犯',
	'强奸',
	'强奸你',
	'後背位',
	'性',
	'性交',
	'性器',
	'性无能',
	'性爱',
	'情色',
	'想上你',
	'懆您妈',
	'懆您娘',
	'懒8',
	'懒八',
	'懒叫',
	'懒教',
	'成人',
	'我操你祖宗十八代',
	'手コキ',
	'扒光',
	'打炮',
	'打飞机',
	'抽插',
	'招妓',
	'拷問',
	'挿入',
	'插你',
	'插死你',
	'撒尿',
	'操你',
	'操你全家',
	'操你奶奶',
	'操你妈',
	'操你娘',
	'操你祖宗',
	'操你老妈',
	'操你老母',
	'操妳',
	'操妳全家',
	'操妳妈',
	'操妳娘',
	'操妳祖宗',
	'操机掰',
	'操比',
	'操逼',
	'支配',
	'放荡',
	'新しいポルノ',
	'日他娘',
	'日你',
	'日你妈',
	'日你老娘',
	'日你老母',
	'日批',
	'月经',
	'机八',
	'机巴',
	'机机歪歪',
	'杂种',
	'正常位',
	'殺人事件',
	'殺人方法',
	'殺し方',
	'毛深い',
	'浪叫',
	'淫',
	'淫乱',
	'淫妇',
	'淫棍',
	'淫水',
	'淫秽',
	'淫荡',
	'淫西',
	'湿透的内裤',
	'潮吹き女',
	'潮吹き男性',
	'激情',
	'灨你娘',
	'烂货',
	'烂逼',
	'爛',
	'狗屁',
	'狗日',
	'狗狼养的',
	'獣姦',
	'玉なめ',
	'玉杵',
	'玉舐め',
	'王八蛋',
	'瓜娃子',
	'瓜婆娘',
	'瓜批',
	'生殖器',
	'ゲイの男性',
	'瘪三',
	'白烂',
	'白痴',
	'白癡',
	'直腸',
	'祖宗',
	'私服',
	'笨蛋',
	'精子',
	'精液',
	'糞',
	'糞便',
	'糞尿愛好症',
	'緊縛',
	'縛り',
	'老二',
	'老味',
	'老母',
	'老瘪三',
	'老骚比',
	'老骚货',
	'肉壁',
	'肉棍子',
	'肉棒',
	'肉缝',
	'肏',
	'肛交',
	'肛門',
	'肥西',
	'脱衣',
	'膣',
	'自己愛性',
	'色情',
	'花柳',
	'茶色のシャワー',
	'荡妇',
	'裸',
	'裸の女性',
	'覗き',
	'誘惑',
	'貞操帯',
	'賤',
	'贝肉',
	'贱B',
	'贱人',
	'贱货',
	'贼你妈',
	'赛你老母',
	'赛妳阿母',
	'赣您娘',
	'足フェチ',
	'足を広げる',
	'ボールを蹴る',
	'輪姦',
	'轮奸',
	'近親相姦',
	'迷药',
	'逼',
	'逼样',
	'野鸡',
	'阳具',
	'阳萎',
	'阴唇',
	'阴户',
	'阴核',
	'阴毛',
	'阴茎',
	'阴道',
	'阴部',
	'陰毛',
	'雞巴',
	'靠北',
	'靠母',
	'靠爸',
	'靠背',
	'靠腰',
	'革抑制',
	'騎上位',
	'驶你公',
	'驶你娘',
	'驶你母',
	'驶你爸',
	'驶你老师',
	'驶你老母',
	'骚比',
	'骚货',
	'骚逼',
	'鬼公',
	'鸡8',
	'鸡八',
	'鸡叭',
	'鸡吧',
	'鸡奸',
	'鸡巴',
	'鸡芭',
	'鸡鸡',
	'黒人',
	'龟儿子',
	'龟头',
);