<?php
/**
 * PHP Array for Norwegian words
 * Delightful sweary additions from:
 * - http://www.youswear.com/index.asp?language=Norwegian
 * - http://www.insults.net/html/swear/norwegian.html
 * - http://www.reddit.com/r/europe/comments/1hzv9d/tell_me_the_best_swearwords_in_your_language/cazmerv
 */

return [
    // General insults and rudeness
    'dritt',
    'drittsekk',
    'dust',
    'faen',
    'fæn',
    'fanden',
    'helvete',
    'helvette',
    'hora',
    'hore',
    'jævel',
    'jævla',
    'kjerring',
    'ludder',
    'pedo',
    'pedofil',
    'pokker',
    'porn',
    'porno',
    'quisling',
    'satan',
    'sattan',
    'søren',

    // Bodily parts and actions
    'bæsj',
    'dildo',
    'ereksjon',
    'fitta',
    'fitte',
    'forpult',
    'fuck',
    'fucking',
    'føkk',
    'føkking',
    'førpult',
    'førrpult',
    'hæstkug',
    'hæstkuk',
    'hestkug',
    'hestkuk',
    'klitoris',
    'klitt',
    'knull',
    'kug',
    'kugost',
    'kuk',
    'kukk',
    'kukkost',
    'kukost',
    'kåt',
    'lort',
    'masturbasjon',
    'masturbere',
    'patte',
    'penis',
    'pess',
    'pikk',
    'piss',
    'pong',
    'pul',
    'pule',
    'pult',
    'pung',
    'pupp',
    'pæss',
    'pæss',
    'rape',
    'rass',
    'rasshøl',
    'rasshøl',
    'rompe',
    'ronk',
    'runk',
    'ræv',
    'ræva',
    'rævhøl',
    'rævva',
    'sæd',
    'shit',
    'skit',
    'sodom',
    'stivas',
    'stiven',
    'utpult',
    'vagina',
    'voldta',
    'voldtekt',

    // Various insults based on bodily parts
    'fittetryne',
    'kukklest',
    'kukkpeis',
    'kukkskalle',
    'kuklest',
    'kukpeis',
    'kukskalle',
    'kuktryne',
    'rasstryne',
    'rautryne',
    'rævtryne',
    'rævvtryne',

    // Racial slurs
    'bruning',
    'hviting',
    'neger',
    'nigger',
    'pakkis',
    'svarting',

    // LGBT slurs
    'homo',
    'homse',
    'lesbe',
    'lespe',
    'pøke',
    'skinkerytter',
    'soper',
    'teppetygger'
];